name: Code quality - lint, typecheck, tests

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  codequality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - run: yarn install

      - name: Linting
        run: yarn lint:js

      - name: Typechecking
        run: yarn tsc:compile

      - name: Testing
        run: yarn test
